apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    app: broker
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - protocol: TCP
      nodePort: 32002
      port: 32002
      targetPort: 32002
  externalTrafficPolicy: Cluster