apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        role: server
      containers:
      - name: server-container
        image: docker.io/miguelriosmarcos/server:v2.1
        ports:
        - containerPort: 32001
        env:
          - name: BROKER_IP
            value: "10.103.149.253" # This is the Cluster IP of the broker